### ISSUE TITLE
🎉 New Extension: Workday

### ISSUE THREAD

**Issue by saimanoj** [poozlehq/poozle#58]

**Comment by harshithmullapudi** [comment]
@saimanoj can you add the openapi spec location if you have any?

**Comment by saimanoj** [comment]
Workday provides open API spec for each API. We need to merge from our end.

https://community.workday.com/sites/default/files/file-hosting/restapi/index.html#absenceManagement/v1/balances

**Comment by harshithmullapudi** [comment]
Closing this issue as we are focusing more on the ticketing vertical. Feel free to reopen this when we start the work again
