### ISSUE TITLE
📝 Docs: Add documentation to Slack

### ISSUE THREAD

**Issue by harshithmullapudi** [poozlehq/poozle#76]
Add documentation for Slack to show up at https://docs.poozle.dev/extensions/slack similar to https://docs.poozle.dev/extensions/github

**Comment by pshri5** [comment]
Hi, I would like to help with the documentation. Could you please help me with the initial resources to start the documentation process?

**Comment by TheJazzDev** [comment]
@harshithmullapudi Could you elaborate more on what needs to be done here please?

**Comment by harshithmullapudi** [comment]
Hey @TheJazzDev before this is built we need to create a  slack integration. Would you be able to pick that?

**Comment by harshithmullapudi** [comment]
Closing this issue as we are focusing more on the ticketing vertical. Feel free to reopen this when we start the work again
