### ISSUE TITLE
🎉 New extension: Customer.io

### ISSUE THREAD

**Issue by saimanoj** [poozlehq/poozle#88]
There is no open API spec for this but there is a Postman collection. We can convert the Postman collection to open API spec using this gist

API: https://customer.io/docs/api/track/

Collection: https://www.postman.com/customerio-docs/workspace/customer-io-apis/collection/23697545-0f7ae1e8-8177-46fc-808a-2fd363dd52b9

Github Gist: https://gist.github.com/saimanoj/86793da5aea590cff58bbd1cb420b534

**Comment by harshithmullapudi** [comment]
Closing this issue as we are focusing more on the ticketing vertical. Feel free to reopen this when we start the work again
