### ISSUE TITLE
🎉 New extension: Paypal

### ISSUE THREAD

**Issue by saimanoj** [poozlehq/poozle#89]
There is no open API spec for this but there is a Postman collection. We can convert the Postman collection to open API spec using this gist

API: https://developer.paypal.com/api/rest/postman/

Collection: https://elements.getpostman.com/redirect?entityId=19024122-92a85d0e-51e7-47da-9f83-c45dcb1cdf24&entityType=collection&workspaceId=345300e6-346e-42e0-aed1-53717919aef0

Github Gist: https://gist.github.com/saimanoj/86793da5aea590cff58bbd1cb420b534

**Comment by harshithmullapudi** [comment]
Closing this issue as we are focusing more on the ticketing vertical. Feel free to reopen this when we start the work again
