### ISSUE TITLE
🎉 New extension: Stripe

### ISSUE THREAD

**Issue by saimanoj** [poozlehq/poozle#91]
Here is the open API spec 

https://api.apis.guru/v2/specs/stripe.com/2022-11-15/openapi.json

**Comment by Sadaf-A** [comment]
@harshithmullapudi Hey, can I pick this up?

**Comment by harshithmullapudi** [comment]
Hey @Sadaf-A thanks for the interest. We are currently in the process of writing the documentation. We will get back to you by End of the week with the details so that you can get started.

**Comment by Sadaf-A** [comment]
@harshithmullapudi That sounds great!

**Comment by harshithmullapudi** [comment]
Hey @Sadaf-A are you still interested in this?

**Comment by Sadaf-A** [comment]
@harshithmullapudi Yes, i am would love to work on it

**Comment by harshithmullapudi** [comment]
Hey @Sadaf-A have you worked before on stripe APIs? Do you have access to stripe APIs?

**Comment by Sadaf-A** [comment]
@harshithmullapudi sadly not, it's my first time

**Comment by harshithmullapudi** [comment]
Hey then could you pick something like google calendar? Which you can easily test?

**Comment by Sadaf-A** [comment]
hey @harshithmullapudi absolutely I'm up for anything. if you could provide link to the issue that would be great

**Comment by harshithmullapudi** [comment]
Hey sure. Could you join our community slack? We are getting the docs ready, we can coordinate there. @Sadaf-A

**Comment by harshithmullapudi** [comment]
Closing this issue as we are focusing more on the ticketing vertical. Feel free to reopen this when we start the work again
